In [1]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier

In [2]:
 %matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import tree
import seaborn as sns
sns.set_palette("Set2")


In [3]:
df= pd.read_excel("/Users/panseeragab/Documents/MSc Fintech with Business Analytics/AI and ML/Coursework 2/Q2.xlsx")
df.tail(10)

Stock   Returns      Risk invest
494  MPWR UW Equity  0.168605  0.938561     No
495  ALGN UW Equity  4.968796  0.944514     No
496  SEDG UW Equity  0.980272  0.952882     No
497   HCA UN Equity  3.667508  1.003435     No
498   TGT UN Equity  5.645821  1.008327     No
499  ENPH UQ Equity  0.574094  1.104357     No
500  ETSY UW Equity  3.286129  1.144679     No
501   UAA UN Equity  6.698171  1.164241     No
502    UA UN Equity  6.950555  1.232631     No
503  DISH UW Equity  5.417060  1.272043     No

In [4]:
X,y = df.drop(['Stock', 'invest'], axis=1),df['invest']

In [5]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 1)

In [6]:
dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)
y_pred = dtc.predict(X_test)
accuracy_score(y_test, y_pred)

0.9868421052631579

In [7]:
rf = RandomForestClassifier(n_estimators=2, max_features="auto",random_state=0)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test, y_pred)


0.9802631578947368

In [8]:
ada = AdaBoostClassifier(n_estimators=100)
ada.fit(X_train, y_train)
y_pred = ada.predict(X_test)
accuracy_score(y_test, y_pred)


0.993421052631579

In [9]:
importances = pd.DataFrame({'feature':X_train.columns,'importance':np.round(dtc.feature_importances_,3)})
importances = importances.sort_values('importance',ascending=False)
importances

feature  importance
1     Risk       0.619
0  Returns       0.381

In [10]:
importances = pd.DataFrame({'feature':X_train.columns,'importance':np.round(rf.feature_importances_,3)})
importances = importances.sort_values('importance',ascending=False)
importances

feature  importance
0  Returns       0.555
1     Risk       0.445

In [11]:
importances = pd.DataFrame({'feature':X_train.columns,'importance':np.round(ada.feature_importances_,3)})
importances = importances.sort_values('importance',ascending=False)
importances

feature  importance
1     Risk        0.86
0  Returns        0.14

In [12]:
data= pd.read_excel("/Users/panseeragab/Documents/MSc Fintech with Business Analytics/AI and ML/Coursework 2/Q2 - Copy.xlsx")

In [13]:
data['is_train'] = np.random.uniform(0, 1, len(data)) <= 0.75
data.tail()

Returns      Risk invest  is_train
499  0.574094  1.104357     No     False
500  3.286129  1.144679     No      True
501  6.698171  1.164241     No      True
502  6.950555  1.232631     No      True
503  5.417060  1.272043     No      True

In [14]:
train, test = data[data['is_train']==True], data[data['is_train']==False]

In [15]:
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:',len(test))

Number of observations in the training data: 372
Number of observations in the test data: 132


In [16]:
features = data.columns[:2]
features

Index(['Returns', 'Risk'], dtype='object')

In [17]:
y = pd.factorize(train['invest'])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [18]:
clf = RandomForestClassifier(n_jobs=2, random_state=1)
clf.fit(train[features], y)

RandomForestClassifier(n_jobs=2, random_state=1)

In [19]:
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
clf.predict_proba(test[features])[0:10]

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [21]:
preds = data.invest[clf.predict(test[features])]

In [22]:
preds[:10]

0    No
0    No
0    No
0    No
0    No
0    No
0    No
0    No
0    No
0    No
Name: invest, dtype: object

In [23]:
test['invest'].head(10)

2     No
3     No
4     No
5     No
7     No
9     No
13    No
15    No
18    No
22    No
Name: invest, dtype: object